version: '3.7'

services:
  development:
    container_name: development
    build:
      context: .
      dockerfile: docker/development.Dockerfile
    volumes:
      - '.:/app'
      - '/app/node_modules'
    ports:
      - 3001:3000
    environment:
      - CHOKIDAR_USEPOLLING=true
  production:
    container_name: production
    build:
      context: .
      dockerfile: docker/production.Dockerfile
    volumes:
      - '.:/app'
  testing:
    container_name: testing
    build:
      context: .
      dockerfile: docker/testing.Dockerfile
    volumes:
      - '.:/app'